export const API = "API";


export const SET_USER_OR_LOGINROUTE = "SET_USER_OR_LOGINROUTE";
export const LOGGEDOUT = "LOGGEDOUT";
export const LOGIN = "LOGIN";
export const SET_LOGINROUTE = "SET_LOGINROUTE";

export const RECEIVE_STATISTICS = "RECEIVE_STATISTICS";
export const RECEIVE_MATCHES = "RECEIVE_MATCHES";
export const RECEIVE_PLAYERS = "RECEIVE_PLAYERS";
export const RECEIVE_PLAYER = "RECEIVE_PLAYER";
export const RECEIVE_MATCH = "RECEIVE_MATCH";
export const REMOVE_MATCH = "REMOVE_MATCH";

export const SET_STATUS = "SET_STATUS";
export const CLEAR_STATUS = "CLEAR_STATUS";
