FROM golang

ARG app_env
ARG backend_url
ENV APP_ENV $app_env
ENV BACKEND_URL $backend_url

WORKDIR /code/scores

RUN go get -u github.com/derekparker/delve/cmd/dlv

COPY . .

WORKDIR /code/scores/cmd/api

RUN go install \
  -ldflags="-X main.version=$(git describe --always --long)" \
  -gcflags "all=-N -l" # turn off optimizations for debugging

ENTRYPOINT [ \
  "/go/bin/dlv", \ 
  "--listen=:40000", \
  "--accept-multiclient", \
  "--log=true", \
  "--api-version=2", \
  "--headless=true", \ 
  "exec", \ 
  "/go/bin/api", \ 
  "--" \
]

CMD [ \
  "-provider", \
  "sqlite3", \ 
  "-connection", \ 
  "/srv/scores/scores.db", \
  "-goauth", \
  "/srv/scores/client_secret.json" \
]

EXPOSE 8080 40000
