FROM golang

ARG app_env
ARG backend_url
ENV APP_ENV $app_env
ENV BACKEND_URL $backend_url

WORKDIR /go/src/github.com/raphi011/scores

RUN go get -u github.com/golang/dep/...
RUN go get -u github.com/derekparker/delve/cmd/dlv

COPY Gopkg.lock .
COPY Gopkg.toml .
RUN dep ensure -vendor-only

COPY . .

WORKDIR /go/src/github.com/raphi011/scores/cmd/api

RUN go install \
  -ldflags="-X main.version=$(git describe --always --long --dirty)" \
  -gcflags "all=-N -l" # turn off optimizations for debugging

CMD [ \
  "/go/bin/dlv", \ 
  "--listen=:40000", \
  "--log=true", \
  "--headless=true", \ 
  "exec", \ 
  "/go/bin/api", \ 
  "--", \
  "-db", \ 
  "/srv/scores/scores.db", \
  "-goauth", \
  "/srv/scores/client_secret.json" \
]

EXPOSE 8080 40000
