export const API = 'API';
export const API_MULTI = 'API_MULTI';

export const SET_USER_OR_LOGINROUTE = 'SET_USER_OR_LOGINROUTE';
export const LOGGEDOUT = 'LOGGEDOUT';
export const SET_LOGINROUTE = 'SET_LOGINROUTE';

export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES';

export const SET_STATUS = 'SET_STATUS';
export const CLEAR_STATUS = 'CLEAR_STATUS';

export const RECEIVE_SCRAPE_JOBS = 'RECEIVE_SCRAPE_JOBS';
